# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: az-np-svc-609-DigAPB-ADT
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name digital-adt003-westus3-vnet-rg --location westus3
      az network vnet create --name adt003-uswest3-vnet --address-prefix 10.4.0.0/23 --resource-group digital-adt003-westus3-vnet-rg --location westus3
    