# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: az-np-svc-609-DigAPB-ADT
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create --name digital-adt001-uswest2-vnet --location westus2
      az network vnet create --name adt001-uswest2-vnet --address-prefix 10.0.0.0/23 
    