name: '$(BuildDefinitionName).$(DayOfYear)$(Rev:.r)'

trigger: none

# Run automatic validation on dependabot branches
# trigger:
#   batch: true
#   branches:
#     include:
#     - component-updates
#     exclude:
#     - dependabot/*

pr: none

pool:
  name: 'adt002-private-agents' # self-hosted agentpool

parameters:
- name: destroyEnvironment
  displayName: "Destroy environment at the end"
  type: boolean
  default: false

variables:
- name:  'environment' # set the environment name as variable
  value: 'adt'
- name: 'synopsys_project_name'
  value: 'DigAPB'

- template: config/configuration.yaml # contains version numbers and global configuration settings
- name:  'workingDirectory'    # Terraform root working directory
  value: 'src/infra/workload'
- name:  'azureServiceConnection' # environment specific service connection
  value: 'az-np-svc-609-DigAPB-ADT'

- template: config/variables-values-${{ variables.environment }}.yaml # contains environment-specific values (non-secret)

stages:

- template: templates/stages-full-release.yaml
  parameters:
    environment: '${{ variables.environment }}'
    destroyOldEnvironment: ${{ parameters.destroyEnvironment }}
    trafficSwitchSteps:
    - 100

- stage: Synopsys_Scanning
  condition: always()
  jobs:
  - job: Synopsys
    steps: 

      - task: SynopsysDetectTask@8
        inputs:
          BlackDuckService: 'Synopsys SBOM Prod'
          DetectArguments: '--detect.project.name=$(synopsys_project_name) --detect.project.version.name=$(Build.SourceBranchName)'
          DetectVersion: 'latest'
          AddTaskSummary: true