parameters:
  workingDirectory:         '' # directory where package.json is located
  jobName:                  '' # name for each build job - needs to be unique within a given stage/pipeline


jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Build UI app'
  steps:

  - task: NodeTool@0
    displayName: 'Use Node v$(uiAppNodeVersion) for UI app'
    inputs:
      versionSpec: '$(uiAppNodeVersion)'

  - task: Npm@1
    displayName: 'NPM install'
    retryCountOnTaskFailure: 1
    inputs:
      command: 'custom'
      customCommand: 'install --prefix .'
      workingDir: '${{ parameters.workingDirectory }}'

  - task: Npm@1
    displayName: 'Build the static UI app for deployment'
    retryCountOnTaskFailure: 1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: '${{ parameters.workingDirectory }}'

  - script: |
      ls
    displayName: check location
    workingDirectory: '${{ parameters.workingDirectory }}'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish built app'
    inputs:
    #this path changes - for the default sample app it's /dist
    # for the costco ui sample app it's /build
      targetPath: '${{ parameters.workingDirectory }}/build'
      artifactName: 'uiApp'
