# Central configuration settings
# used for E2E environment pipelines
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'adt001'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix

# The first value in 'stampLocations' is the primary region used for global services.
# IMPORTANT! Changing the primary region (first value) is a BREAKING change and will destroy CosmosDB and Front Door.
- name: 'stampLocations'
  value: '["westus3"]'    # Check which regions are valid. There is a list in /src/infra/README.md  This shoulod be a comma seperated list for running in multiple regions

# Terraform state variables
- name:  'terraformResourceGroup'
  value: '$(prefix)-terraformstate-rg'      
- name:  'terraformStorageAccount'
  value: '$(prefix)tfstatestore'     

# Other settings
- name:  'contactEmail'
  value: 'cberon@costco.com'  # <===== CHANGE THIS VALUE TO THE ENVIRONMENT OWNER GROUP

  # Custom DNS name settings
- name: 'envDnsZoneRG'
  value: 'digital-adt-dns-rg'                         # <===== CHANGE THIS VALUE
- name: 'envDomainName'
  value: 'adt001.az.digital.ct-costco.com'     # <===== CHANGE THIS VALUE